##00. PyTorch Fundamentals
Resources: https://www.learnpytorch.io/ & https://www.youtube.com/watch?v=Z_ikDlimN6A

In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.0+cu118


## Introduction to Tensors

### Creating tensors

In [7]:
# scaler

scaler = torch.tensor(7)
scaler

tensor(7)

In [8]:
scaler.ndim

0

In [9]:
scaler.item()

7

In [13]:
# vector

vector = torch.tensor([5,5,5])
vector

tensor([5, 5, 5])

In [14]:
vector.ndim

1

In [15]:
vector.shape

torch.Size([3])

In [19]:
# matrix

matrix = torch.tensor([[5,5,5],[6,6,6],[7,7,7]])

In [20]:
matrix.ndim

2

In [21]:
matrix.shape

torch.Size([3, 3])

In [25]:
# tensor

TENSOR = torch.tensor([[[5,5],[6,6],[7,7]],[[2,2],[3,3],[4,4]]])

In [26]:
TENSOR.ndim

3

In [27]:
TENSOR.shape

torch.Size([2, 3, 2])

In [30]:
TENSOR[0]

tensor([[5, 5],
        [6, 6],
        [7, 7]])

## Random Tensors

torch.rand(): https://pytorch.org/docs/stable/generated/torch.rand.**html**

In [33]:
# Random Tensors

random_tensor = torch.rand(2,3,2)
random_tensor

tensor([[[0.2702, 0.0991],
         [0.5957, 0.8459],
         [0.2445, 0.2394]],

        [[0.7625, 0.1320],
         [0.2619, 0.8770],
         [0.3181, 0.6105]]])

In [31]:
random_tensor_second = torch.rand(4,7,3)
random_tensor_second

tensor([[[0.5867, 0.1586, 0.0337],
         [0.2722, 0.1353, 0.7756],
         [0.7210, 0.6765, 0.8755],
         [0.7507, 0.9290, 0.8473],
         [0.6083, 0.3433, 0.3647],
         [0.3871, 0.1564, 0.0631],
         [0.0917, 0.1917, 0.2544]],

        [[0.6614, 0.7706, 0.5066],
         [0.1594, 0.6926, 0.8014],
         [0.5680, 0.5781, 0.7514],
         [0.9034, 0.3166, 0.7673],
         [0.8750, 0.3636, 0.7654],
         [0.7872, 0.6268, 0.8428],
         [0.7240, 0.4063, 0.9142]],

        [[0.0035, 0.8116, 0.9787],
         [0.0515, 0.0884, 0.4983],
         [0.4273, 0.8601, 0.6253],
         [0.6402, 0.5261, 0.4780],
         [0.2736, 0.3021, 0.2268],
         [0.0348, 0.3296, 0.9905],
         [0.1834, 0.5263, 0.0858]],

        [[0.3325, 0.1277, 0.0480],
         [0.9951, 0.7119, 0.1310],
         [0.0098, 0.8436, 0.6578],
         [0.3088, 0.1117, 0.5571],
         [0.9714, 0.8627, 0.7720],
         [0.2081, 0.3810, 0.3365],
         [0.2568, 0.2132, 0.6169]]])

In [34]:
random_tensor.ndim

3

In [35]:
random_tensor.dtype

torch.float32

In [30]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color_channels(R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [37]:
# Create a tensor of all zeros

zeros = torch.zeros(size=(2,3,4))
zeros, zeros.dtype

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 torch.float32)

In [39]:
# Create a tensor of all ones

ones = torch.ones(size=(2, 3, 4))
ones, ones.dtype

(tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 torch.float32)

## Creating a range and tensors like

In [36]:
# Use torch.arange(), torch.range() is deprecated

zero_to_ten_deprecated = torch.range(0,10) # Note: this may return an error in the future

torch.arange(0,10)

<ipython-input-36-349583921c9e>:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0,10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
# Create a range of values 0 to 10

zero_to_ten = torch.arange(start=1, end=50, step=3)
zero_to_ten

tensor([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [42]:
x = torch.arange(0, 1999, 125)
x

tensor([   0,  125,  250,  375,  500,  625,  750,  875, 1000, 1125, 1250, 1375,
        1500, 1625, 1750, 1875])

In [43]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=x) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Getting information from tensors

In [44]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.6710, 0.4560, 0.7134, 0.5915],
        [0.1673, 0.4870, 0.1013, 0.0397],
        [0.4041, 0.6656, 0.8172, 0.8843]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Tensor Operations

In [45]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [44]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [45]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [46]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [46]:
# Can also use torch functions
torch.multiply(tensor, 100)

tensor([100, 200, 300])

In [47]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


### Matrix multiplication

In [48]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [49]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [50]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

## Finding the min, max, mean, sum, etc (aggregation)

In [51]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [52]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [53]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0
